### ISSUE TITLE
Question: Migrate to pure React Native

### ISSUE THREAD

**Issue by phuongwd** [jar0s/reactNative-babel-wla#2]
Hello,
Thanks for great setup, 

Just for understand, could you share why did you migrate to pure React Native?

And other question, could we run multiple branch at same time in development?

Thank you,

**Comment by jar0s** [comment]
Hi @phuongwd,
Expo hides the details of native setup/config for Android and iOS, which is great for simple applications as you don't need to worry about them.
The whitelabelled setup (or multi-brand as some call it) is quite non-standard and requires customisations in the native setup/config for both Android and iOS. That's why I needed to "eject" from Expo and move to pure React Native.

As for your second question, I'm not sure I fully understand what do you mean by "branch" in this case.
If you're asking whether it's possible to run apps for multiple brands at once, then the answer would be "not out of the box". The `yarn configure-brand` command sets the project up to work with one brand at a time. It should be possible to modify this to enable running multiple brands at once, although it wasn't the intention.
Please let me know if that answers your question.
Cheers

**Comment by phuongwd** [comment]
Thanks for quick response.
My bad, I meant "brand".

Because we will have the use cases such as we have to verify multiple brands when changes some points, ...
It would be cool if we can run multiple brands.

**Comment by jar0s** [comment]
Switching between the brands doesn't take too long, but I hear what you say.
The original idea was that each developer (or team) would be focused on one brand at a time and that there will be a set of automated tests verifying if nothing got broken in other brands.
Having said that, it feels possible to make it work the way you'd like with running multiple bundler processes (each on different port and with different set of env vars) and changing the `yarn configure-brand` and dev build stage a bit.
If you'd like help with setting this up, feel free to reach out to me on LinkedIn.
